# Column Widths
ANNOTATION_WIDTH = 3
CONTROL_BOARD_WIDTH = 3
VISUALIZATION_WIDTH = 9
MAX_VISUALIZATION_WIDTH = 12

# Figure Heights
FIGURE_HEIGHT = 1000

# Tab Settings
TAB_SIDEBAR_WIDTH = 2
TAB_MAIN_CONTENT_WIDTH = 10
